version: '2'
services:
  overheardclub-app:
    image: overheardclub
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://overheardclub-postgresql:5432/overheardclub
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8076:8076
  overheardclub-postgresql:
    extends:
      file: postgresql.yml
      service: overheardclub-postgresql
